### ISSUE TITLE
Can't install to Extensions

### ISSUE THREAD

**Issue by faizalfaridzi** [fa0311/danbooru-to-prompt#3]
the Error said: Manifest file is missing or unreadable. Could not load manifest.

**Comment by fa0311** [comment]
What browser?

**Comment by faizalfaridzi** [comment]
Google Chrome

**Comment by fa0311** [comment]
The [install](https://github.com/fa0311/danbooru-to-prompt#install) link was incorrect and has just been corrected.
Please try again.

**Comment by fa0311** [comment]
Resolved?

**Comment by faizalfaridzi** [comment]
Yes, thank you
