### ISSUE TITLE
i think you upload the wrong files

### ISSUE THREAD

**Issue by Bambinata** [fa0311/danbooru-to-prompt#4]
the files install an extension named twitter-multiple-video-play-assistant instead of danbooru to prompt
![Screenshot 2022-10-18 104549](https://user-images.githubusercontent.com/28219772/196330709-aa559200-0a30-42c3-b249-8b92d86dbe4c.png)

**Comment by fa0311** [comment]
Already fixed. [2daf79a7b68b22f6e180758195f855cea7e98e0f](https://github.com/fa0311/danbooru-to-prompt/commit/2daf79a7b68b22f6e180758195f855cea7e98e0f)
Please try again.

**Comment by Bambinata** [comment]
yup, fixed already
